# Generated by Django 3.2.4 on 2021-06-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
